### PR TITLE
[PLAT-381] Update winning condition to be 3 squares !!! DO NOT MERGE !!!

### LINKED ISSUE #7: wrong winning conditions?
image

### PR DESCRIPTION
**Pull request by cowboy-bebug**
Update the winning condition from `4 stones in a row` -> `3 squares (of 4 stones)` as described in the design doc.

Resolves #7

### CODE REVIEW

File: dot4gravity/src/lib.rs [hunk 1]
```diff
@@ -456,7 +456,7 @@ impl<Player: PartialEq + Clone> Game<Player> {
         mut game_state: GameState<Player>,
         player: Player,
         side: Side,
-        position: u8,
+        position: Position,
     ) -> Result<GameState<Player>, GameError> {
         Self::can_drop_stone(&game_state, &side, position, &player)?;
         let player_index = game_state.player_index(&player);
```
Comment (andyjsbell) [inline dot4gravity/src/lib.rs:462]: could it be clearer to define the `usize` type we use here instead of within the array lookups below?

**Review by andyjsbell — APPROVED** [review]
lgtm 👍
