### PR TITLE
[Issue 6] add checks for dropping stone

### LINKED ISSUE #6: panick, when dropping a stone at a locked position.
image

Trying to drop a stone here at West 7, where there is already a stone, will panic.

```
worker_1      | thread '<unnamed>' panicked at 'index out of bounds: the len is 10 but the index is 255', /root/.cargo/git/checkouts/ajuna-games-9c75f15c32f67658/159ae6d/dot4gravity/src/lib.rs:151:9
worker_1      | note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
worker_1      | fatal runtime error: failed to initiate panic, error 5
```

### PR DESCRIPTION
**Pull request by cowboy-bebug**
Changes:
- rename `InvalidStonePosition` -> `InvalidStonePosition` (for consistency with `InvalidBombPosition`)
- move and implement `is_inside_board` check inside `Bound` trait
- add `Cell.is_stone()`, `Side.bound_coordinates()`, `Board.is_stone_droppable()` to be used inside `can_drop_stone` check
- update `can_drop_stone` to check for `GamePhase::Player` (else return `DroppedStoneDuringBombPhase` error)
- add tests accordingly

Closes #6.

### CODE REVIEW

File: dot4gravity/src/lib.rs [hunk 1]
```diff
@@ -68,6 +71,10 @@ impl Cell {
     fn is_explodable(&self) -> bool {
         *self != Cell::Block
     }
+
+    fn is_stone(&self) -> bool {
+        !matches!(self, Cell::Stone(_))
```
Comment (raulmartinezm) [inline dot4gravity/src/lib.rs]: To check that it's a stone, shouldn't we spare the negation?

File: dot4gravity/src/tests.rs [hunk 2]
```diff
@@ -313,12 +324,61 @@ fn a_stone_dropped_on_a_stone() {
...
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, o, o, o, o, o, o, o, o, x],
+        [x, x, x, x, x, x, x, x, x, x],
+    ];
```
Comment (raulmartinezm) [inline dot4gravity/src/tests.rs]: should it be tested for blocks as well? (changing the stones in the bounds to blocks)

**Review by raulmartinezm — COMMENTED** [review]
Great work, just left a couple of comments

File: dot4gravity/src/lib.rs [hunk 3]
```diff
@@ -142,6 +155,10 @@ impl Board {
         position.is_inside_board() && self.get_cell(position).is_explodable()
     }
 
+    fn is_stone_droppable(&self, position: &Coordinates) -> bool {
+        position.is_inside_board() && self.get_cell(position).is_stone()
```
Comment (DidacSF) [inline dot4gravity/src/lib.rs]: Should this check be like this:
```rust
position.is_inside_board() && self.get_cell(position).is_empty()
```

The way I understand it, this method should only return true if our position is in an empty cell right?

File: dot4gravity/src/lib.rs [hunk 4]
```diff
@@ -299,15 +318,22 @@ impl<Player: PartialEq> Game<Player> {
...
         game_state: &GameState<Player>,
-        position: u8,
+        side: Side,
+        position: Position,
         player: &Player,
     ) -> Result<(), GameError> {
-        if position >= BOARD_HEIGHT || position >= BOARD_WIDTH {
-            return Err(GameError::InvalidDroppingPosition);
+        if game_state.phase != GamePhase::Play {
+            return Err(GameError::DroppedStoneDuringBombPhase);
```
Comment (DidacSF) [inline dot4gravity/src/lib.rs]: I would change this enum error to something that matches the condition evaluated, maybe something like `DroppedStoneDuringNonPlayPhase` or similar

File: dot4gravity/src/lib.rs [hunk 5]
```diff
@@ -399,7 +425,7 @@ impl<Player: PartialEq + Clone> Game<Player> {
         side: Side,
```
Comment (DidacSF) [inline dot4gravity/src/lib.rs:421]: We can change `side` to take a `&Side` and also change `Self::can_drop_stone` to also take a `&Side` in order to avoid cloning the `side` variable.

File: dot4gravity/src/lib.rs (hunk 1 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: Ah yes thanks for spotting!

File: dot4gravity/src/tests.rs (hunk 2 above)
Comment (cowboy-bebug) [reply dot4gravity/src/tests.rs]: Yep sounds good :+1:

File: dot4gravity/src/lib.rs (hunk 3 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: My bad, `is_stone` seems confusing - I'll update it to be something like
```rust
impl Cell {
    fn is_stone_droppable(&self) -> bool {
        !matches!(self, Cell::Block | Cell::Stone(_))
    }
}
```

Yes, a stone can be dropped on either Empty or Bomb (which will trigger explosion)

File: dot4gravity/src/lib.rs (hunk 4 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: Sounds good :+1: I'll change the other one as well to match

File: dot4gravity/src/lib.rs (hunk 5 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs:421]: Nice catch! Thanks :pray:

**Review by DidacSF — APPROVED** [review]
