### PR TITLE
[Issue 7] remove concrete PlayerIndex type from GameState

### LINKED ISSUE #7: wrong winning conditions?
image

### PR DESCRIPTION
**Pull request by cowboy-bebug**
Removing the concrete `PlayerIndex` type from `GameState`.

For more context, this was part of a workaround to avoid propagating the generic `Player` type all the way down from `GameState` -> `Cell` (see the `Bomb` and `Stone` variants below): https://github.com/ajuna-network/ajuna-games/blob/1850d8d6c16a47e6e6c9cd47e01c4edd1918123f/dot4gravity/src/lib.rs#L43-L48

Closes #7.

### CODE REVIEW

**Review by raulmartinezm — APPROVED** [review]
Great

File: dot4gravity/src/lib.rs [hunk 1]
```diff
@@ -223,16 +223,16 @@ pub struct GameState<Player> {
...
     /// When present,it contains the player that won.
-    pub winner: Option<PlayerIndex>,
+    pub winner: Option<Player>,
     /// Next player turn.
-    pub next_player: PlayerIndex,
+    pub next_player: Player,
     /// Players:
     pub players: [Player; NUM_OF_PLAYERS],
     /// Number of bombs available for each player.
     pub bombs: [(Player, u8); NUM_OF_PLAYERS],
```
Comment (DidacSF) [inline dot4gravity/src/lib.rs]: It think that have `winner`, `next_player` and `bombs` use `PlayerIndex` instead of player will make it more clear that those three fields depend on what's stored in the `players` field, it will also help in reducing the amount of clones we need to done, possibly even allow us to remove the `Clone` restrictions on some implementations and methods for `Player`

File: dot4gravity/src/lib.rs [hunk 2]
```diff
@@ -274,12 +274,23 @@ impl<Player: PartialEq> GameState<Player> {
             .expect("game to always start with 2 players") as u8;
         player_index
     }
+
+    fn next_player(&self) -> Player {
```
Comment (DidacSF) [inline dot4gravity/src/lib.rs]: Maybe we can make do only returning `&Player` ?

File: dot4gravity/src/lib.rs (hunk 1 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: I agree but the frontend client needs to display the information as they are without indexing. We're using more chain storage to persist these Player types but each game state gets removed at the end so should be alright.

Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: Actually let's ask if this is required, otherwise let's just close this PR :)

File: dot4gravity/src/lib.rs (hunk 2 above)
Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: Yep that's more readable

File: dot4gravity/src/lib.rs (hunk 1 above)
Comment (DidacSF) [reply dot4gravity/src/lib.rs]: @andyjsbell Do we need to use `Player` for the fields above to that they can be displayed in the frontend? Or we can use the `PlayerIndex` instead?

Comment (andyjsbell) [reply dot4gravity/src/lib.rs]: I would think `Player` is clearer and not inferred. Would we also have to read twice to determine the winner?

Comment (DidacSF) [reply dot4gravity/src/lib.rs]: Yeah, if winner contained `PlayerIndex` then we would, so then it's better to leave it as `Player` if that is a concern

Comment (cowboy-bebug) [reply dot4gravity/src/lib.rs]: Cool let's stick to `Player` for clarity for now.
